### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by computeronix**
Updated README to discuss the temperature-units variable

### CODE REVIEW

**Comment by computeronix** [comment]
-Modified README to have user install the agent in the /opt directory
-Added crontab command
-Added line for every 30 seconds update

**Comment by computeronix** [comment]
Were you able to get this approved if these pull requests make sense?

**Comment by suda** [comment]
@computeronix Thanks again Bill :) Seeing how much you are contributing to this project, would you like to be become an official contributor?

**Comment by computeronix** [comment]
?Sure :)


Also have two more pull requests and should be good :)


Bill McIlhargey
317.315.3869
bill@mcilhargey.com
________________________________

**Comment by suda** [comment]
Great! I added you as collaborator, so you should be able to merge those PR's :)

**Comment by computeronix** [comment]
Thanks!  Done!


Also going to add a section how to setup your own dashing server with raspberry pi   in readme of dashing-mining-dashboard  (pretty short).  I could not get heroku working for the life of me, it would keep erroring out on the code for some reason when uploaded.  But my own server works perfectly


Appreciate all the work you have done in this!!  Nice product!


Bill McIlhargey
317.315.3869
bill@mcilhargey.com
________________________________

**Pull request merged**
